### ISSUE TITLE
AbstractMethodError after start

### ISSUE THREAD

**Issue by Htarlov** [src-d/gemini#221]
I have strange error when trying to hash a standard (not siva) repository:

```
WARN 13:13:32 org.apache.spark.internal.Logging$class (Logging.scala:66) - Set SPARK_LOCAL_IP if you need to bind to another address`
Running Hashing as Apache Spark job, master: local[*]
Hashing 4 repositories in: '../preprocessed/' ()
... (list here)
Exception in thread "main" java.lang.AbstractMethodError
	at org.apache.spark.internal.Logging$class.initializeLogIfNecessary(Logging.scala:99)
	at tech.sourced.gemini.cmd.HashSparkApp$.initializeLogIfNecessary(HashSparkApp.scala:38)
	at org.apache.spark.internal.Logging$class.log(Logging.scala:46)
	at tech.sourced.gemini.cmd.HashSparkApp$.log(HashSparkApp.scala:38)
	at tech.sourced.gemini.cmd.HashSparkApp$.delayedEndpoint$tech$sourced$gemini$cmd$HashSparkApp$1(HashSparkApp.scala:173)
	at tech.sourced.gemini.cmd.HashSparkApp$delayedInit$body.apply(HashSparkApp.scala:38)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at tech.sourced.gemini.cmd.HashSparkApp$.main(HashSparkApp.scala:38)
	at tech.sourced.gemini.cmd.HashSparkApp.main(HashSparkApp.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

I work on Ubuntu 18.04 with docker 17.06.0-ce build 02c1d87 and docker-compose version 1.16.1, build 6d1ac21. Anyone got similar problem or can reproduce?

**Comment by Htarlov** [comment]
Stupid me, used wrong command.

Should:
- have copied folder to ./repositories
- use command:
`docker-compose exec gemini ./hash -f standard /repositories/preprocessed`
